// Re-export Lucide React icons for backward compatibility
// All custom SVG icons have been replaced with Lucide equivalents
export {
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  FileText as FileTextIcon,
  GraduationCap as GraduationCapIcon,
  Lightbulb as LightbulbIcon,
  List as ListIcon,
  Loader2 as Loader2Icon,
  LogOut as LogOutIcon,
  Menu as MenuIcon,
  MessageSquare as MessageSquareIcon,
  Moon as MoonIcon,
  CheckCircle as RadixCheckCircledIcon,
  Check as RadixCheckIcon,
  ChevronDown as RadixChevronDown,
  ChevronLeft as RadixChevronLeft,
  ChevronRight as RadixChevronRight,
  Code as RadixCodeIcon,
  XCircle as RadixCrossCircledIcon,
  Circle as RadixDotFilledIcon,
  Info as RadixInfoCircledIcon,
  Zap as RadixLightningBoltIcon,
  BookOpen as RadixReaderIcon,
  Star as RadixStarIcon,
  Settings as SettingsIcon,
  Shuffle as ShuffleIcon,
  Sun as SunIcon,
  User as UserIcon,
  X as XIcon,
} from "lucide-react";
